from typing import Protocol

class BaseInverter(Protocol):
    async def read_all_registers(self) -> None: ...
    async def check_connection(self) -> bool: ...
    def get_registers_as_json(self) -> dict: ...
    async def disconnect(self) -> None: ...
