class Config:
    ESP_READER_HOST = "192.168.30.182"
    ESP_READERPORT = 6053
    ESP_READERENCRYPTION_KEY = "004Nt8RGUB3CMOGb9vnY3sCblsx8vYbZSwrSwE2UbOE="
    ESP_READERWINDOW_SECONDS = 0.5

    SOLAR_EDGE_INVERTER_DEVICE = "/dev/ttyUSB0"
    SOLAR_EDGE_INVERTER_BAUD = 9600
    SOLAR_EDGE_INVERTER_TIMEOUT = 2


def load_config():
    return Config
